### ISSUE TITLE
Robotcad is installed through AddonManager but not available in Workbench list

### ISSUE THREAD

**Issue by Vladimat** [drfenixion/freecad.robotcad#32]
![image](https://github.com/user-attachments/assets/fa348538-444c-4102-8d30-d010bdc55fae)
![image](https://github.com/user-attachments/assets/07b57714-c45e-4e6f-9a01-36d9d634f009)

Ubuntu 22.04, 24.04; Freecad 21.2, FreeCAD 1.0rc2

**Comment by drfenixion** [comment]
Check FreeCAD Report View for errors and add them here if exists. 

In theory RobotCAD can conflict with CROSS, try to remove CROSS.

**Comment by Vladimat** [comment]
Yes, w/o CROSS it works. Now it generates another error, but it's inherited from CROSS:
"<class 'ModuleNotFoundError'>: No module named 'geometry_msgs'
10:19:44  Running the Python command 'GetPlanningScene' failed:
Traceback (most recent call last):
  File "/home/vladdy/.local/share/FreeCAD/Mod/freecad.robotcad/freecad/cross/ui/command_get_planning_scene.py", line 33, in Activated
    fcgui.addModule('freecad.cross.planning_scene_proxy')

No module named 'geometry_msgs'"
