### ISSUE TITLE
Update `package.xml` to show this workbench conflicts with CROSS

### ISSUE THREAD

**Issue by luzpaz** [drfenixion/freecad.robotcad#43]
@drfenixion Please add a [conflict tag](https://wiki.freecad.org/Package_Metadata#%3Cconflict%3E) to the [`package.xml`](https://github.com/drfenixion/freecad.robotcad/blob/main/package.xml) to avoid future issues with CROSS workbench

_Originally posted by @luzpaz in https://github.com/drfenixion/freecad.robotcad/issues/32#issuecomment-2468874440_

**Comment by drfenixion** [comment]
Ok, thank you for contribution.

**Comment by drfenixion** [comment]
Done
https://github.com/drfenixion/freecad.robotcad/commit/f618b8370867a5c466db4b38df04c250c41f6dab
